# Generated by Django 4.2.4 on 2023-10-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_productgallary_productgallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='banner/banners'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
