# Generated by Django 4.2.4 on 2023-10-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_banner_description_product_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
