# Generated by Django 4.2.4 on 2023-10-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_shipping_option_alter_product_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
